create table app_users (
    id uuid primary key,
    username varchar(255) not null,
    name varchar(255) not null,
    password varchar(255),
    provider varchar(20) not null,
    provider_id varchar(255),
    guest_device_id varchar(36),
    phone varchar(50),
    avatar_image_id uuid,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    user_type varchar(255),
    enabled boolean not null default true,
    account_locked boolean not null default false,
    account_expires_at timestamp(6) with time zone,
    credentials_expire_at timestamp(6) with time zone,
    failed_login_attempts integer not null default 0,
    locked_at timestamp(6) with time zone,
    last_login_at timestamp(6) with time zone,
    deleted boolean not null default false,
    constraint uk_app_users_username unique (username),
    constraint uk_app_users_provider_id unique (provider_id),
    constraint uk_app_users_guest_device_id unique (guest_device_id),
    constraint uk_app_users_phone unique (phone)
);

create table user_roles (
    app_user_id uuid not null,
    role varchar(255),
    constraint fk_user_roles_app_user foreign key (app_user_id) references app_users (id)
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    app_user_id uuid not null,
    token_hash varchar(128) not null,
    device_id varchar(255) not null,
    device_name varchar(255),
    device_type varchar(50),
    ip_address varchar(45),
    user_agent text,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    revoked_reason varchar(255),
    replaced_by_token_hash varchar(128),
    constraint fk_refresh_token_user foreign key (app_user_id) references app_users (id),
    constraint uk_refresh_tokens_token_hash unique (token_hash)
);

create index idx_refresh_token_user on refresh_tokens (app_user_id);
create unique index idx_refresh_token_hash on refresh_tokens (token_hash);
create index idx_refresh_token_device on refresh_tokens (app_user_id, device_id);
create index idx_refresh_token_expires on refresh_tokens (expires_at);
create index idx_refresh_token_created on refresh_tokens (created_at);
